### ISSUE TITLE
UE5 (Jusant)

### ISSUE THREAD

**Issue by donizettilorenzo** [cdozdil/CyberXeSS#1]
Can you tell how to install the dlls, because there are *4* nvngx folders! DLSS vs DLSSG ("Streamline") and each has a "development" subfolder :D

And about libxess?

**Comment by donizettilorenzo** [comment]
Using the proxy: https://i.postimg.cc/ZKFLnd5H/Senza-titolo.jpg

(Intel Arc A380)

**Comment by cdozdil** [comment]
Hi,

Please download latest release from [here](https://github.com/cdozdil/CyberXeSS/releases/tag/v0.2) and unzip into game folder. If thats an Unreal game find the game exe in Win64 folder and unzip file there.

If you didn't used CyberFsr etc. before please download and run [this reg file](https://raw.githubusercontent.com/cdozdil/CyberXeSS/master/EnableSignatureOverride.reg) to enable DLSS signature override.

Finally UE5 games have some issues with internal resolution, please find and update section below in nvngx.ini.

```ini
[QualityOverrides]
; Set this to true to enable custom quality mode overrides
; true or false - Default (auto) is false
;QualityRatioOverrideEnabled=auto

; Set custom upscaling ratio for each quality mode
;
; Default (auto) values:
; Ultra Quality         : 1.3
; Quality               : 1.5
; Balanced              : 1.7
; Performance           : 2.0
; Ultra Performance     : 2.5
;
;QualityRatioUltraQuality=auto
;QualityRatioQuality=auto
;QualityRatioBalanced=auto
;QualityRatioPerformance=auto
;QualityRatioUltraPerformance=auto

; If you have flickering problem in an Unreal Engine game
; you may try these values instead of default ones!
;
QualityRatioOverrideEnabled=true
;
QualityRatioUltraQuality=1.25
QualityRatioQuality=1.4285714286
QualityRatioBalanced=1.6666666667
QualityRatioPerformance=2.0
QualityRatioUltraPerformance=2.5
```

You can always check our [Discord channel](https://discord.com/channels/995299945492008990/1131520508475752489) for more help

**Comment by donizettilorenzo** [comment]
Damn!
Wrong reg file ahah! "Enable Override Signature" and I did read "Disable Signature" 
This+DXGI=working! Thanks!

**Comment by donizettilorenzo** [comment]
No way, it doesn't work.
In Horizon Zero Dawn the option is now visible but the game crashes loading the savegame

**Comment by cdozdil** [comment]
Ok will check on my side, will keep you updated
