### ISSUE TITLE
Horizon Zero Dawn: XeSS working but white viewport (FSR22 working)

### ISSUE THREAD

**Issue by donizettilorenzo** [cdozdil/CyberXeSS#2]
(i've removed nvngx_dlss because I'm testing CyberXeSS on an NV system but it doesn't make a difference with or without it)
The frame is just white but with the correct HUD. Audio is there, game is running good.
No problem with FSR22 (it's really good compared to the game-bundled FSR1.x).
No dxgi/nvapi.

**Comment by cdozdil** [comment]
Hi,

Could you retry it with AutoExposure set to true in `nvngx.ini`?

```ini
AutoExposure=true
```
